Repository kss761036/Epigram, pull requests merged in 2025-04, with the labels that each got.

#230 Feat/229/페이지이동_최상단고정
  src/app/layout.tsx
  src/components/ScrollToTop.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#233 Bug/231/상세댓글 수정
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramComments.tsx
  src/components/Comment.test.tsx
  src/components/Comment.tsx
Labels: Priority: High 🔥, Type: Bug :bug:, Type: Improve UX :arrow_up:

#235 Test/222/검색페이지통합테스트
  cypress/e2e/login.cy.ts
  cypress/e2e/search.cy.ts
  cypress/e2e/signup.cy.ts
  cypress/support/commands.ts
  src/app/(after-login)/search/_components/SearchResult.tsx
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#237 Test/224/메인페이지 통합테스트
  cypress/e2e/epigrams.cy.ts
  src/app/(after-login)/epigrams/page.tsx
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#238 Test/234/에피그램_작성페이지_통합테스트
  cypress/e2e/create-epigram.cy.ts
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#243 Test/232/마이페이지 통합테스트
  cypress/e2e/mypage.cy.ts
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#246 Feat/242/seo
  public/open-bg.png
  src/apis/epigram/epigram.service.ts
  src/app/(after-login)/epigrams/[id]/edit/layout.tsx
  src/app/(after-login)/epigrams/[id]/layout.tsx
  src/app/(after-login)/epigrams/[id]/opengraph-image.tsx
  src/app/(after-login)/epigrams/create/layout.tsx
  src/app/(after-login)/epigrams/layout.tsx
  src/app/(after-login)/feeds/layout.tsx
  src/app/(after-login)/mypage/layout.tsx
  src/app/(after-login)/search/layout.tsx
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/(before-login)/(auth)/signup/page.tsx
  src/app/layout.tsx
  src/app/opengraph-image.png
  src/assets/fonts/IropkeBatang.woff
  src/utils/truncateText.test.ts
  src/utils/truncateText.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#244 Bug/241/랜딩페이지하단버튼영역수정
  src/app/(before-login)/(landing)/_components/CTASection.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:

#245 Bug/240/TodayMood컴포넌트쿼리키수정
  src/apis/emotion/emotion.queries.ts
  src/components/TodayMood.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#249 Test/232/피드페이지통합테스트
  cypress/e2e/feeds.cy.ts
  cypress/support/index.d.ts
  cypress/tsconfig.json
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#247 Test/239/랜딩페이지통합테스트
  cypress/e2e/landing.cy.ts
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#251 Feat/250/라우팅개선
  public/IropkeBatang.woff
  src/app/(after-login)/epigrams/[id]/opengraph-image.tsx
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/components/headers/AfterLogin.tsx
  src/middleware.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#253 Test/252/통합테스트수정
  cypress/e2e/feeds.cy.ts
  cypress/e2e/search.cy.ts
  cypress/tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#257 Test/254/에피그램_수정페이지_통합테스트
  cypress/e2e/edit-epigram.cy.ts
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#259 Test/248/상세페이지통합테스트
  cypress/e2e/detail.cy.ts
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#265 UX/264/토스트스타일추가
  src/app/layout.tsx
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#267 Refactor266/로그인회원가입리액트훅폼수정
  src/app/(before-login)/(auth)/_components/LoginForm.tsx
  src/app/(before-login)/(auth)/_components/SignupForm.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#277 Refactor/270/ModalBase컴포넌트 제어방식확장
  src/components/DeleteModal.tsx
  src/components/ModalBase.tsx
  src/components/ProfileModal.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#275 Refactor/274/접근성개선
  src/app/(before-login)/(auth)/_components/AuthWrapper.tsx
  src/components/Calendar.tsx
  src/components/Dropdown.test.tsx
  src/components/Dropdown.tsx
  src/components/EmotionFilter.tsx
  src/components/IconButton.tsx
  src/components/Input.stories.ts
  src/components/Input.test.tsx
  src/components/Input.tsx
  src/components/MoreMenu.tsx
  src/components/headers/AfterLogin.tsx
  src/components/headers/BeforeLogin.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#272 Refactor/271/마이페이지개선
  cypress/e2e/mypage.cy.ts
  src/app/(after-login)/epigrams/_components/TodayEmotion.tsx
  src/app/(after-login)/epigrams/_components/TodayEpigram.tsx
  src/app/(after-login)/epigrams/page.tsx
  src/app/(after-login)/mypage/_components/MonthlyLogs.tsx
  src/app/(after-login)/mypage/_components/MyEmotions.tsx
  src/app/(after-login)/mypage/page.tsx
  src/components/Calendar.test.tsx
  src/components/Chart.tsx
  src/components/TodayMood.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#278 Refactor/276/검색페이지개선
  src/app/(after-login)/search/_components/SearchHeader.stories.ts
  src/app/(after-login)/search/_components/SearchHeader.tsx
  src/app/(after-login)/search/page.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#280 Refactor/273/유효성메시지 매직넘버 상수화
  src/apis/auth/auth.type.ts
  src/apis/comment/comment.type.ts
  src/apis/epigram/epigram.type.ts
  src/apis/user/user.type.ts
  src/components/Button.test.tsx
  src/components/Chip.test.tsx
  src/components/EmojiButton.test.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#283 Refactor/282/에피그램작성 코드수정
  src/apis/epigram/epigram.queries.ts
  src/app/(after-login)/epigrams/[id]/edit/page.tsx
  src/app/(after-login)/epigrams/create/page.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#287 Refactor/285/모달접근성개선
  src/app/(after-login)/epigrams/_components/detail/DetailHeader.tsx
  src/app/(after-login)/mypage/_components/MyProfile.tsx
  src/app/(after-login)/mypage/_components/ProfileEditModal.tsx
  src/components/DeleteModal.tsx
  src/components/Dropdown.tsx
  src/components/ModalBase.tsx
  src/components/MoreMenu.tsx
  src/components/ProfileModal.tsx
  src/utils/focusTrap.ts
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:, Type: Refactor :recycle:

#286 Refactor/284/댓글컴포넌트_리팩토링
  src/app/(after-login)/epigrams/_components/RecentComment.tsx
  src/app/(after-login)/mypage/_components/CommentList.tsx
  src/app/(after-login)/mypage/_components/MyWritings.tsx
  src/components/Comment.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#293 Bug/292/댓글버튼이동방지
  src/components/Comment.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#291 Refactor/288/탭접근성
  src/app/(after-login)/mypage/_components/MyWritings.tsx
  src/components/Tab.stories.tsx
  src/components/Tab.test.tsx
  src/components/Tab.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#295 Bug/294/댓글프로필이동방지
  src/components/Comment.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:

#297 Refator/296/댓글작성 리팩토링
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramComments.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailContent.tsx
  src/components/Comment.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:, Type: Refactor :recycle:

#301 Docs/300/readme업데이트
  README.md
Labels: Priority: Medium :bookmark:, Type: Doc :memo:

#303 Docs/302/readme레이아웃
  README.md
Labels: Priority: Low 🐢, Type: Doc :memo:

#305 Docs/304/readme링크수정
  README.md
Labels: Type: Doc :memo:
