Repository kss761036/Epigram, pull requests merged in 2025-03, with the labels that each got.

#4 [#3] Test/자동 배포 테스트
  src/app/page.tsx
Labels: bug

#8 [#7] Docs/깃 세팅관련 문서 수정
  .github/ISSUE_TEMPLATE/test.yaml
  .github/workflows/ci.yaml
  .github/workflows/setup-label.yaml
  .prettierrc
  next.config.ts
Labels: Priority: Medium :bookmark:, Type: Doc :memo:

#10 [#9] Test/디스코드 훅 테스트
  package-lock.json
  package.json
  src/app/page.tsx
Labels: Priority: Low 🐢, Type: Test :test_tube:

#12 [#11] Chore/스토리북, 제스트 라이브러리 설치
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  eslint.config.mjs
  jest.config.cjs
  jest.setup.js
  package-lock.json
  package.json
  src/app/__tests__/example.test.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/ButtonTest.stories.ts
  src/stories/ButtonTest.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  tsconfig.json
  vitest.config.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#14 [#13] Bug/깃 세팅 수정 및 라이브러리 설치
  .commitlintrc.json
  .husky/commit-msg
  .husky/pre-commit
  eslint.config.mjs
  package-lock.json
  package.json
  src/stories/Header.tsx
  src/stories/Page.tsx
Labels: Priority: High 🔥, Type: Bug :bug:, Type: Doc :memo:

#17 [#16] Test/테스트
  README.md
Labels: Priority: Low 🐢, Type: Test :test_tube:

#28 Bug/25/테일윈드 color변수 globals.css 수정
  src/assets/css/globals.css
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Doc :memo:

#26 Feat/22/아이콘컴포넌트
  src/components/Emoji.path.tsx
  src/components/Emoji.stories.ts
  src/components/Emoji.test.tsx
  src/components/Emoji.tsx
  src/components/Icon.path.tsx
  src/components/Icon.stories.ts
  src/components/Icon.test.tsx
  src/components/Icon.tsx
  src/stories/Icongraphy.mdx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#33 Feat/23/필드컴포넌트
  src/assets/css/globals.css
  src/components/Input.stories.ts
  src/components/Input.test.tsx
  src/components/Input.tsx
  src/components/TextArea.stories.ts
  src/components/TextArea.test.tsx
  src/components/TextArea.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#35 Feat/34/스토리북메인배포
  .github/workflows/storybook-main.yaml
Labels: Priority: High 🔥

#37 Fix/36/스토리북배포수정
  .github/workflows/storybook-main.yaml
Labels: Priority: High 🔥, Type: Bug :bug:

#40 Feat/32/아바타컴포넌트
  next.config.ts
  src/components/Avatar.stories.ts
  src/components/Avatar.test.tsx
  src/components/Avatar.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#42 Bug/38/필드컴포넌트 기능수정
  src/components/Input.stories.ts
  src/components/Input.tsx
  src/components/TextArea.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Bug :bug:

#44 Fix/43/이모지컴포넌트타입수정
  src/components/Avatar.tsx
  src/components/Emoji.path.tsx
  src/components/Emoji.stories.ts
  src/components/Emoji.test.tsx
  src/components/Emoji.tsx
  src/types/common.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#45 Feat/30/토글_라디오_컴포넌트_추가
  src/components/Radio.stories.tsx
  src/components/Radio.test.tsx
  src/components/Radio.tsx
  src/components/Toggle.stories.tsx
  src/components/Toggle.test.tsx
  src/components/Toggle.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Test :test_tube:

#46 Feat/39/버튼컴포넌트
  .storybook/preview.ts
  src/components/Button.stories.ts
  src/components/Button.test.tsx
  src/components/Button.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#47 Feat/29/칩컴포넌트
  src/components/Chip.stories.ts
  src/components/Chip.test.tsx
  src/components/Chip.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#50 Refactor/49/토글_라디오_리팩토링
  src/components/Radio.stories.tsx
  src/components/Radio.test.tsx
  src/components/Radio.tsx
  src/components/Toggle.stories.tsx
  src/components/Toggle.test.tsx
  src/components/Toggle.tsx
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:, Type: Refactor :recycle:

#52 Feat/24/로그인기능
  package-lock.json
  package.json
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/(before-login)/(auth)/signup/page.tsx
  src/app/AuthSession.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/middleware.ts
  src/types/next-auth.d.ts
  src/utils/validationSchema.ts
  tsconfig.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#53 Feat/48/아이콘버튼컴포넌트
  src/components/IconButton.stories.ts
  src/components/IconButton.test.tsx
  src/components/IconButton.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#55 Fix/54/스토리북폰트교체
  .storybook/preview.ts
  .storybook/style.css
Labels: Priority: High 🔥, Type: Bug :bug:

#59 Feat/41/차트컴포넌트
  package-lock.json
  package.json
  src/components/Chart.legend.test.tsx
  src/components/Chart.legend.tsx
  src/components/Chart.stories.tsx
  src/components/Chart.test.tsx
  src/components/Chart.tsx
  src/types/common.ts
  src/utils/getPercentage.test.ts
  src/utils/getPercentage.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#61 Feat/51/기타버튼
  src/components/EtcButton.stories.tsx
  src/components/EtcButton.test.tsx
  src/components/EtcButton.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#64 Refactor/63/차트컴포넌트개선
  package-lock.json
  package.json
  src/components/Chart.legend.test.tsx
  src/components/Chart.legend.tsx
  src/components/Chart.stories.tsx
  src/components/Chart.test.tsx
  src/components/Chart.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#65 62/Feat/카드_컴포넌트
  public/notebook-bg.svg
  src/components/Card.stories.ts
  src/components/Card.test.tsx
  src/components/Card.tsx
  src/components/SearchCard.stories.ts
  src/components/SearchCard.test.tsx
  src/components/SearchCard.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#68 Feat/67/캘린더컴포넌트
  package-lock.json
  package.json
  src/components/Calendar.stories.ts
  src/components/Calendar.test.tsx
  src/components/Calendar.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#69 Feat/66/댓글_컴포넌트
  package-lock.json
  package.json
  src/components/Comment.stories.ts
  src/components/Comment.test.tsx
  src/components/Comment.tsx
  src/utils/formatTime.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#70 Feat/60/드롭다운컴포넌트
  src/components/Dropdown.test.tsx
  src/components/Dropdown.tsx
  src/components/EmojiButton.stories.tsx
  src/components/EmojiButton.test.tsx
  src/components/EmojiButton.tsx
  src/components/EmotionFilter.stories.tsx
  src/components/EmotionFilter.test.tsx
  src/components/EmotionFilter.tsx
  src/components/MoreMenu.stories.tsx
  src/components/MoreMenu.test.tsx
  src/components/MoreMenu.tsx
  src/types/common.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#73 Chore/72/댓글_수정
  next.config.ts
  src/components/Comment.stories.ts
  src/components/Comment.test.tsx
  src/components/Comment.tsx
Labels: Priority: Low 🐢, Type: Doc :memo:, Type: Refactor :recycle:

#77 Docs/74/readme작성
  README.md
Labels: Priority: Low 🐢, Type: Doc :memo:

#75 Feat/58/카카오로그인
  package-lock.json
  package.json
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/(before-login)/(auth)/oauth/kakao/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/kakao/route.ts
  src/app/layout.tsx
  src/context/AuthSession.tsx
  src/hooks/useAuth.ts
  src/hooks/useLogout.ts
  src/middleware.ts
  src/utils/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#86 Refactor/85/소셜로그인개선
  src/app/(before-login)/(auth)/login/google/page.tsx
  src/app/(before-login)/(auth)/login/kakao/page.tsx
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/api/auth/oauth/[provider]/callback/route.ts
  src/app/api/auth/oauth/[provider]/route.ts
  src/utils/auth.ts
  src/utils/nextauth.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#87 Feat/78/랜딩페이지
  src/app/(before-login)/(landing)/_components/CTASection.tsx
  src/app/(before-login)/(landing)/_components/HeroSection.tsx
  src/app/(before-login)/(landing)/_components/ServiceSection.tsx
  src/app/(before-login)/(landing)/_components/Zigzag.tsx
  src/app/(before-login)/(landing)/page.tsx
  src/assets/img/landing/EveryDayMo.png
  src/assets/img/landing/EveryDayPC.png
  src/assets/img/landing/sectionImg1.png
  src/assets/img/landing/sectionImg2.png
  src/assets/img/landing/sectionImg3.png
  src/assets/img/landing/sectionImg4.png
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#88 Feat/79/섹션_컴포넌트_구현
  src/components/Section.stories.tsx
  src/components/Section.test.tsx
  src/components/Section.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Test :test_tube:

#92 Feat/90/프로필모달컴포넌트
  src/components/DeleteModal.tsx
  src/components/ProfileModal.stories.tsx
  src/components/ProfileModal.test.tsx
  src/components/ProfileModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Test :test_tube:

#93 Feat/84/서비스함수
  package-lock.json
  package.json
  src/apis/auth/auth.service.ts
  src/apis/auth/auth.type.ts
  src/apis/comment/comment.service.ts
  src/apis/comment/comment.type.ts
  src/apis/emotion/emotion.service.ts
  src/apis/emotion/emotion.type.ts
  src/apis/epigram/epigram.service.ts
  src/apis/epigram/epigram.type.ts
  src/apis/user/user.service.ts
  src/apis/user/user.type.ts
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/(before-login)/(auth)/signup/page.tsx
  src/app/api/[...endpoint]/route.ts
  src/context/QueryProvider.tsx
  src/types/common.ts
  src/utils/axios.ts
  src/utils/nextauth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#97 Bug/96/소셜로그인버그수정
  src/apis/auth/auth.service.ts
  src/app/(before-login)/(auth)/login/google/page.tsx
  src/app/(before-login)/(auth)/login/kakao/page.tsx
  src/app/api/auth/oauth/[provider]/callback/route.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#94 Feat/80/탭_컴포넌트_구현
  src/components/Tab.stories.tsx
  src/components/Tab.test.tsx
  src/components/Tab.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Test :test_tube:

#99 Feat/98/인증페이지작업
  src/apis/auth/auth.type.ts
  src/app/(before-login)/(auth)/_components/AuthWrapper.test.tsx
  src/app/(before-login)/(auth)/_components/AuthWrapper.tsx
  src/app/(before-login)/(auth)/_components/LoginForm.tsx
  src/app/(before-login)/(auth)/_components/OauthWrapper.tsx
  src/app/(before-login)/(auth)/_components/SignupForm.tsx
  src/app/(before-login)/(auth)/_components/Social.tsx
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/(before-login)/(auth)/oauth/google/page.tsx
  src/app/(before-login)/(auth)/oauth/kakao/page.tsx
  src/app/(before-login)/(auth)/signup/page.tsx
  src/assets/css/globals.css
  src/assets/img/auth/icon-google.svg
  src/assets/img/auth/icon-kakao.svg
  src/assets/img/auth/icon-naver.svg
  src/assets/img/common/logo.svg
  src/components/FormError.tsx
  src/components/Spinner.stories.tsx
  src/components/Spinner.test.tsx
  src/components/Spinner.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#102 Ux/91/랜딩페이지추가작업
  package-lock.json
  package.json
  src/app/(before-login)/(landing)/_components/AnimatedText.tsx
  src/app/(before-login)/(landing)/_components/CTASection.tsx
  src/app/(before-login)/(landing)/_components/HeroSection.tsx
  src/app/(before-login)/(landing)/_components/ServiceSection.tsx
  src/assets/img/landing/EveryDay.svg
  src/assets/img/landing/EveryDayMo.png
  src/assets/img/landing/EveryDayPC.png
  src/assets/img/landing/SectionImg1Mo.svg
  src/assets/img/landing/SectionImg1PC.svg
  src/assets/img/landing/SectionImg1Tab.svg
  src/assets/img/landing/SectionImg2Mo.svg
  src/assets/img/landing/SectionImg2PC.svg
  src/assets/img/landing/SectionImg2Tab.svg
  src/assets/img/landing/SectionImg3Mo.svg
  src/assets/img/landing/SectionImg3PC.svg
  src/assets/img/landing/SectionImg3Tab.svg
  src/assets/img/landing/SectionImg4Mo.svg
  src/assets/img/landing/SectionImg4PC.svg
  src/assets/img/landing/SectionImg4Tab.svg
  src/assets/img/landing/sectionImg1.png
  src/assets/img/landing/sectionImg2.png
  src/assets/img/landing/sectionImg3.png
  src/assets/img/landing/sectionImg4.png
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#105 Feat/101/검색페이지작업
  package-lock.json
  package.json
  src/apis/epigram/epigram.queries.ts
  src/app/(after-login)/search/_components/SearchHeader.stories.ts
  src/app/(after-login)/search/_components/SearchHeader.tsx
  src/app/(after-login)/search/_components/SearchRecent.stories.ts
  src/app/(after-login)/search/_components/SearchRecent.tsx
  src/app/(after-login)/search/_components/SearchResult.stories.tsx
  src/app/(after-login)/search/_components/SearchResult.tsx
  src/app/(after-login)/search/_components/SearchWrapper.tsx
  src/app/(after-login)/search/_components/useRecent.test.ts
  src/app/(after-login)/search/_components/useRecent.tsx
  src/app/(after-login)/search/page.tsx
  src/components/Input.tsx
  src/components/SearchCard.tsx
  src/hooks/useLocalStorage.test.ts
  src/hooks/useLocalStorage.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#107 Feat/106/세션프로필이미지추가
  next.config.ts
  src/types/next-auth.d.ts
  src/utils/nextauth.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:

#112 Feat/109/에러페이지
  src/app/error.tsx
  src/app/not-found.tsx
  src/components/ErrorFallback.stories.tsx
  src/components/ErrorFallback.test.tsx
  src/components/ErrorFallback.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#114 Ux/113/검색페이지헤더영역수정
  src/app/(after-login)/layout.tsx
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#121 Bug/120/버튼타입수정
  src/app/(before-login)/(auth)/_components/Social.tsx
  src/components/Dropdown.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#119 Feat/118/auth개선
  src/apis/user/user.service.ts
  src/apis/user/user.type.ts
  src/app/(after-login)/layout.tsx
  src/components/headers/AfterLogin.tsx
  src/middleware.ts
  src/utils/nextauth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#124 Bug/123/오늘의감정버그수정
  src/apis/emotion/emotion.queries.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#126 Feat/125/에피그램카드타입개선
  src/app/(after-login)/search/_components/SearchResult.tsx
  src/components/Card.tsx
  src/components/SearchCard.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:

#127 Feat/117/마이페이지 월별기록
  package-lock.json
  src/app/(after-login)/mypage/_components/MonthlyLogs.tsx
  src/app/(after-login)/mypage/_components/MyCalendar.tsx
  src/app/(after-login)/mypage/page.tsx
  src/components/Calendar.stories.tsx
  src/components/Calendar.test.tsx
  src/components/Calendar.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#129 Feat/122/피드페이지
  src/apis/epigram/epigram.queries.ts
  src/app/(after-login)/feeds/page.tsx
  src/app/(after-login)/search/_components/useRecent.tsx
  src/hooks/useLocalStorage.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#132 Bug/131/로컬스토리지훅 테스트코드 수정
  src/hooks/useLocalStorage.test.ts
Labels: Priority: High 🔥, Type: Bug :bug:, Type: Test :test_tube:

#130 Feat/110/에피그램 작성
  src/apis/epigram/epigram.type.ts
  src/app/(after-login)/addepigram/page.tsx
  src/app/layout.tsx
  src/components/Radio.stories.tsx
  src/components/Radio.test.tsx
  src/components/Radio.tsx
  src/components/headers/AfterLogin.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Bug :bug:, Type: Test :test_tube:

#134 Feat/128/마이페이지 오늘의감정
  src/apis/emotion/emotion.queries.ts
  src/app/(after-login)/mypage/_components/MonthlyLogs.tsx
  src/app/(after-login)/mypage/_components/MyProfile.tsx
  src/app/(after-login)/mypage/_components/MyWritings.tsx
  src/app/(after-login)/mypage/page.tsx
  src/components/TodayMood.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#136 Feat/133/에피그램_수정_페이지
  src/app/(after-login)/addepigram/page.tsx
  src/app/(after-login)/epigrams/[id]/edit/page.tsx
  src/components/EpigramForm.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#138 Feat/103/메인페이지
  src/apis/comment/comment.queries.ts
  src/app/(after-login)/epigrams/_components/RecentComment.tsx
  src/app/(after-login)/epigrams/_components/RecentEpigram.tsx
  src/app/(after-login)/epigrams/_components/TodayEpigram.tsx
  src/app/(after-login)/epigrams/page.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#137 Bug/135/피드카드정렬 및 효과 추가
  src/app/(after-login)/feeds/page.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Improve UX :arrow_up:

#142 Feat/141/리프레시토큰로직
  src/types/next-auth.d.ts
  src/utils/axios.ts
  src/utils/nextauth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#144 Feat/143/토큰유효기간개선
  package-lock.json
  package.json
  src/utils/axios.ts
  src/utils/nextauth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#146 Feat/145/메인페이지영역분리
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramComments.tsx
  src/app/(after-login)/epigrams/_components/EpigramDetail.tsx
  src/app/(after-login)/search/_components/SearchWrapper.tsx
  src/app/(before-login)/(auth)/_components/AuthWrapper.tsx
  src/components/Inner.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#151 Feat/140/마이페이지 탭
  src/apis/epigram/epigram.queries.ts
  src/apis/epigram/epigram.service.ts
  src/apis/user/user.queries.ts
  src/apis/user/user.service.ts
  src/app/(after-login)/mypage/_components/MyComments.tsx
  src/app/(after-login)/mypage/_components/MyEpigrams.tsx
  src/app/(after-login)/mypage/_components/MyWritings.tsx
  src/app/(after-login)/mypage/page.tsx
  src/assets/img/empty.png
  src/types/common.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#155 Feat/150/상세페이지상단작업
  src/apis/epigram/epigram.queries.ts
  src/apis/epigram/epigram.service.ts
  src/apis/epigram/epigram.type.ts
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramDetail.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailContent.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailFooter.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailHeader.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailLoading.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailWrapper.tsx
  src/app/(after-login)/epigrams/_components/detail/index.tsx
  src/assets/img/common/paper.svg
  src/utils/nextauth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#156 Refactor/139/랜딩 메인페이지리팩토링
  src/app/(after-login)/epigrams/_components/RecentComment.tsx
  src/app/(after-login)/epigrams/_components/RecentEpigram.tsx
  src/app/(after-login)/epigrams/page.tsx
  src/app/(before-login)/(landing)/_components/CTASection.tsx
  src/app/(before-login)/(landing)/_components/HeroSection.tsx
  src/app/(before-login)/(landing)/page.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Bug :bug:, Type: Refactor :recycle:

#157 Refactor/154/에피그램_폼_리팩토링
  src/apis/epigram/epigram.type.ts
  src/app/(after-login)/epigrams/[id]/edit/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramForm.tsx
  src/app/(after-login)/epigrams/create/page.tsx
  src/components/EpigramForm.tsx
  src/components/Radio.tsx
Labels: Priority: Medium :bookmark:, Type: Doc :memo:, Type: Refactor :recycle:

#161 Refactor/147/persist
  src/app/(after-login)/feeds/page.tsx
  src/app/(after-login)/search/_components/useRecent.test.ts
  src/app/(after-login)/search/_components/useRecent.tsx
  src/app/(after-login)/search/page.tsx
  src/hooks/useLocalStorage.test.ts
  src/hooks/useLocalStorage.ts
  src/store/feedsListTypeStore.ts
  src/store/recentSearchStore.ts
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#162 Refactor/158/apiproxy
  src/app/api/[...endpoint]/route.ts
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#165 Feat/160/에피그램작성버튼
  src/app/(after-login)/_components/FloatingButtons.tsx
  src/app/(after-login)/feeds/page.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#167 Ux/166/상세페이지 삭제 확인 프로세스 추가
  src/app/(after-login)/epigrams/_components/EpigramDetail.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#168 Bug/159/메인페이지오류수정
  src/apis/emotion/emotion.queries.ts
  src/app/(after-login)/epigrams/page.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:, Type: Bug :bug:

#170 Refactor/169/최근검색어개선
  src/store/feedsListTypeStore.test.ts
  src/store/recentSearchStore.test.ts
  src/store/recentSearchStore.ts
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#171 Refactor/149/검색결과개선
  src/app/(after-login)/feeds/page.tsx
  src/app/(after-login)/search/_components/SearchResult.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#174 Refactor/173/오늘의에피그램수정
  src/apis/epigram/epigram.queries.ts
  src/app/(after-login)/epigrams/_components/TodayEpigram.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#175 Feat/152/마이페이지 댓글수정삭제
  src/apis/comment/comment.queries.ts
  src/app/(after-login)/mypage/_components/MyComments.tsx
  src/app/(after-login)/mypage/_components/MyEpigrams.tsx
  src/app/(after-login)/mypage/_components/MyWritings.tsx
  src/components/Comment.stories.ts
  src/components/Comment.test.tsx
  src/components/Comment.tsx
  src/components/CommentEditForm.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#179 Feat/176/댓글 프로필모달연결
  src/apis/comment/comment.queries.ts
  src/components/Comment.tsx
  src/hooks/useModal.ts
Labels: Priority: High 🔥, Type: Feature :sparkles:, Type: Refactor :recycle:

#182 Bug/181/댓글_컴포넌트_수정삭제버튼_변경
  src/components/Comment.stories.ts
  src/components/Comment.test.tsx
  src/components/Comment.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#184 Feat/180/통합테스트셋팅
  cypress.config.ts
  cypress/e2e/test.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#187 Feat/185/좋아요개선, Feat/186/상세페이지 SSR
  src/apis/epigram/epigram.queries.ts
  src/apis/epigram/epigram.service.ts
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramDetail.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#189 Feat/188/상세페이지로딩추가
  src/app/(after-login)/epigrams/[id]/loading.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#193 Bug/192/api프록시개선
  src/apis/user/user.service.ts
  src/app/api/[...endpoint]/route.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#195 Feat/178/프로필수정모달
  src/app/(after-login)/mypage/_components/MyProfile.tsx
  src/app/(after-login)/mypage/_components/ProfileEditModal.tsx
  src/app/(after-login)/mypage/_components/UploadPreview.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#198 Refactor/194/헤더컴포넌트개선
  src/components/headers/AfterLogin.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#191 Feat/183/상세페이지_댓글_구현
  src/apis/comment/comment.queries.ts
  src/apis/epigram/epigram.queries.ts
  src/app/(after-login)/epigrams/_components/EpigramComments.tsx
  src/app/(after-login)/epigrams/_components/RecentComment.tsx
  src/app/(after-login)/mypage/_components/CommentList.tsx
  src/app/(after-login)/mypage/_components/MyWritings.tsx
  src/components/CommentForm.tsx
Labels: Priority: High 🔥, Type: Feature :sparkles:, Type: Refactor :recycle:

#201 Bug/200/프로필사진업로드개선
  src/apis/user/user.service.ts
  src/components/Avatar.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#204 Refactor/203/middleware개선
  src/middleware.ts
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#205 Feat/172/TodayMood스토리북테스트추가
  src/components/TodayMood.stories.tsx
  src/components/TodayMood.test.tsx
Labels: Priority: Low 🐢, Type: Doc :memo:, Type: Test :test_tube:

#202 Refactor/마이페이지 Inner컴포넌트적용
  src/app/(after-login)/mypage/_components/MyEpigrams.tsx
  src/app/(after-login)/mypage/page.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#211 Bug/207/리프레시 토큰 개선
  src/context/AuthSession.tsx
  src/utils/nextauth.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#215 Feat/213/상세페이지개선
  src/app/(after-login)/epigrams/[id]/loading.tsx
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/_components/EpigramDetail.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailFooter.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailLoading.tsx
  src/app/(after-login)/epigrams/_components/detail/DetailWrapper.tsx
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#214 Feat/210/API-Proxy개선
  src/app/api/[...endpoint]/route.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#212 Bug/209/댓글더보기개수변경
  src/apis/comment/comment.queries.ts
  src/app/(after-login)/epigrams/_components/RecentComment.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#219 Refactor/218/쿼리키네이밍리팩터링
  src/apis/comment/comment.queries.ts
  src/apis/emotion/emotion.queries.ts
  src/apis/epigram/epigram.queries.ts
  src/apis/user/user.queries.ts
Labels: Priority: High 🔥, Type: Refactor :recycle:

#220 Refactor/216/프로필수정모달개선
  src/app/(after-login)/mypage/_components/MyProfile.tsx
  src/app/(after-login)/mypage/_components/ProfileEditModal.tsx
  src/components/ModalBase.tsx
  src/hooks/useModalStore.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#221 Test/217/회원가입로그인통합테스트
  cypress.config.ts
  cypress/e2e/login.cy.ts
  cypress/e2e/signup.cy.ts
  cypress/support/commands.ts
  cypress/support/index.d.ts
Labels: Priority: Medium :bookmark:, Type: Test :test_tube:

#226 Refactor/206/댓글 rhf + zod 기반으로 리팩토링
  src/apis/epigram/epigram.type.ts
  src/app/(after-login)/epigrams/_components/EpigramComments.tsx
  src/app/(after-login)/epigrams/_components/RecentComment.tsx
  src/app/(after-login)/mypage/_components/CommentList.tsx
  src/components/CommentForm.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:
